### ISSUE TITLE
Hello, wang. Your work is valuable and promising. Could you please provide a rough date to public your code? Look forward to it. 

### ISSUE THREAD

**Issue by Y-Sisyphus** [yuz1wan/video_distillation#1]

**Comment by Y-Sisyphus** [comment]
Hello, wang. Your work is valuable and promising. Could you please provide a rough date to public your code? Look forward to it.

**Comment by yuz1wan** [comment]
Hello,

Thank you for your interest in our work! We have released the preview version of the code. If you have any questions, please feel free to contact me.
