### ISSUE TITLE
Could you release a distilled dataset?

### ISSUE THREAD

**Issue by Wu-ssssss** [yuz1wan/video_distillation#3]
I am so curious what a video will look like when distilled.

**Comment by yuz1wan** [comment]
Yes, of course. We can provide some [checkpoints](https://drive.google.com/drive/folders/1bHs8mfupeCmXE8ZodjIuCV6iXs7cFf_n?usp=sharing) of distilled videos.

We have provided a visualized result of DM+Ours HMDB51 spc2 dpc2 at /HMDB51/DM+Ours/ (every row is a synthetic 16-frame video). 

We also provide a Jupyter Notebook to convert the checkpoint back into frames.

**Comment by Wu-ssssss** [comment]
Thanks for your reply!

I have tried the vis.ipynb and some problems occurred. Is the sta.pt omitted? I don't actually know which .pt file corresponds to "path_static".

> Yes, of course. We can provide some [checkpoints](https://drive.google.com/drive/folders/1bHs8mfupeCmXE8ZodjIuCV6iXs7cFf_n?usp=sharing) of distilled videos.
> 
> We have provided a visualized result of DM+Ours HMDB51 spc2 dpc2 at /HMDB51/DM+Ours/ (every row is a synthetic 16-frame video).
> 
> We also provide a Jupyter Notebook to convert the checkpoint back into frames.

**Comment by yuz1wan** [comment]
Apologies for the delayed response, as I've been dealing with some critical deadlines recently. "sta.pt" refers to our static memory, which you can train yourself. Of course, we also provide our pre-trained [static memory](https://drive.google.com/drive/folders/1v6VlW0Ohmu5rDgamTqDeQFiMMIZpKl3v?usp=sharing) (as mentioned in the README file).

**Comment by Wu-ssssss** [comment]
> Apologies for the delayed response, as I've been dealing with some critical deadlines recently. "sta.pt" refers to our static memory, which you can train yourself. Of course, we also provide our pre-trained [static memory](https://drive.google.com/drive/folders/1v6VlW0Ohmu5rDgamTqDeQFiMMIZpKl3v?usp=sharing) (as mentioned in the README file).

Thanks a lot! :muscle:
