### ISSUE TITLE
How to train a model with full-dataset and coreset selection strategies?

### ISSUE THREAD

**Issue by Zi-YuanYang** [yuz1wan/video_distillation#4]
Thanks for the code sharing. This work is interesting, but I met some problems in using the code. 

I wander that how to train the model with the full-dataset or with a certain coreset selection strategy? Besides, is the "UCF101actions.pkl" necessary?

**Comment by yuz1wan** [comment]
Hi! Thanks for your interest in our work!  

For full-dataset training, you can use the dataloaders in distill_utils/dataset.py and **evaluate_synset** function(with mode = 'none') in utils.py.  

For coreset selection strategy, we refer to [k-center baseline](https://github.com/VICO-UoE/DatasetCondensation/issues/21) for k-center strategy and [herding baseline](https://github.com/VICO-UoE/DatasetCondensation/issues/15) for herding strategy. We can provide the [code](https://drive.google.com/file/d/1le_q-bADbCjISGFrNYSKWILXoQ9lVGTR/view?usp=sharing) we used, but it has not yet been thoroughly organized. We will expedite the organization process and add it to the repository as soon as possible. Should you encounter any issues, please feel free to reach out to me, and I will be more than happy to assist you.

**Comment by Zi-YuanYang** [comment]
Thanks for your quick response. I'm downloading the Kine-400 dataset, I noticed that this dataset is really large. I wander that how much storage space do I need to store the preprocessed data. I'm afraid that I don't have enough space to store the preprocessed data to continue my reasearch.

**Comment by yuz1wan** [comment]
The complete Kinetics400 dataset is over 400+G in size, and after preprocessing, it is about 18G.

**Comment by Zi-YuanYang** [comment]
> The complete Kinetics400 dataset is over 400+G in size, and after preprocessing, it is about 18G.

Thanks for the kind information. It really helps a lot. Have a nice day~
