### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by codejie-hub** [yuz1wan/video_distillation#5]
In the data directory under distill_utils in the warehouse,
UCF101 RGB:[Part 1](http://ftp.tugraz.at/pub/feichtenhofer/tsfusion/data/ucf101_jpegs_256.zip.001) 
[Part 2](http://ftp.tugraz.at/pub/feichtenhofer/tsfusion/data/ucf101_jpegs_256.zip.002)
 [Part 3](http://ftp.tugraz.at/pub/feichtenhofer/tsfusion/data/ucf101_jpegs_256.zip.003)
HMDB51 RGB: [Part 1](https://ftp.tugraz.at/pub/feichtenhofer/tsfusion/data/hmdb51_jpegs_256.zip) 
The download address is invalid. Can you provide it?thank you!

**Comment by yuz1wan** [comment]
Hi, these download links are provided by [twostreamfusion](https://github.com/feichtenhofer/twostreamfusion). Now I’m also unable to open these links. Perhaps you can open an issue in that repo, contact [feichtenhofer](https://github.com/feichtenhofer), and ask what happened.

**Comment by codejie-hub** [comment]
ok, thank you.
